-- Data: permissions (formato module:action, igual que edificio-alcazar)

INSERT INTO permissions (name, module) VALUES
  ('users:read', 'users'),
  ('users:create', 'users'),
  ('users:update', 'users'),
  ('users:delete', 'users'),
  ('users:assign_roles', 'users'),
  ('job_titles:read', 'job_titles'),
  ('job_titles:create', 'job_titles'),
  ('job_titles:update', 'job_titles'),
  ('job_titles:delete', 'job_titles'),
  ('roles:read', 'roles'),
  ('roles:create', 'roles'),
  ('roles:update', 'roles'),
  ('roles:delete', 'roles'),
  ('permissions:read', 'permissions'),
  ('permissions:create', 'permissions'),
  ('permissions:update', 'permissions'),
  ('permissions:delete', 'permissions'),
  ('companies:read', 'companies'),
  ('companies:create', 'companies'),
  ('companies:update', 'companies'),
  ('companies:delete', 'companies'),
  ('projects:read', 'projects'),
  ('projects:create', 'projects'),
  ('projects:update', 'projects'),
  ('projects:delete', 'projects'),
  ('assets:read', 'assets'),
  ('assets:create', 'assets'),
  ('assets:update', 'assets'),
  ('assets:delete', 'assets'),
  ('tickets:read', 'tickets'),
  ('tickets:create', 'tickets'),
  ('tickets:update', 'tickets'),
  ('tickets:delete', 'tickets'),
  ('tickets:change_status', 'tickets'),
  ('tickets:assign', 'tickets'),
  ('ticket_comments:read', 'ticket_comments'),
  ('ticket_comments:create', 'ticket_comments'),
  ('ticket_comments:read_internal', 'ticket_comments'),
  ('audit_logs:read', 'audit_logs'),
  ('system:manage', 'system')
ON CONFLICT (name) DO NOTHING;
